limit: 1
streamers:
  ? ../Videolingo/batch/output\BREAKING： Democrats WIN VOTE to RELEASE Epstein files\BREAKING：
    Democrats WIN VOTE to RELEASE Epstein files.webm
  : copyright: 2
    source: null
    no_reprint: 1
    tid: 207
    cover: ../Videolingo/batch/output\BREAKING： Democrats WIN VOTE to RELEASE Epstein
      files\BREAKING： Democrats WIN VOTE to RELEASE Epstein files.jpg
    title: '[重磅] 公布Epstein案文件！民主党这波操作绝了 #欧美焦点'
    desc_format_id: 0
    desc: 喜欢的话就狠狠地点个赞吧！也别忘了分享给志同道合的朋友～如果你也喜欢这类风格，记得收藏关注一下！家人们的支持就是我持续更新的“充电宝”，你们每一个点赞留言我都认真看！❤️
    dolby: 1
    lossless_music: 1
    tag: 时装周,Fashion Week,高级定制,T台秀,设计师品牌,奢侈品,潮流,时尚
    dynamic: ''
    dtime: 1753462800
